# Generated by Django 6.0.5 on 2026-05-23 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('website', 'Website'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('etsy', 'Etsy')], max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_sold_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='products.product')),
            ],
        ),
    ]
