# Generated by Django 6.0.5 on 2026-05-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('stock_changed', 'Stock Changed'), ('price_changed', 'Price Changed'), ('order_received', 'Order Received')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=15)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
