# Generated by Django 6.0.5 on 2026-05-23 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('website', 'Website'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('etsy', 'Etsy'), ('google', 'Google Shopping')], max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Setup')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500)),
                ('store_id', models.CharField(blank=True, max_length=255)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_inventory', models.BooleanField(default=True)),
                ('sync_prices', models.BooleanField(default=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_push', 'Product Push'), ('stock_update', 'Stock Update'), ('price_update', 'Price Update'), ('order_pull', 'Order Pull'), ('full_sync', 'Full Sync')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
